# Generated by Django 4.1.3 on 2022-11-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=5)),
                ('secret_key', models.CharField(blank=True, default='', max_length=14)),
                ('target_url', models.URLField(max_length=2048)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
